sudo: required
services:
  - postgresql
addons:
  postgresql: "9.4"
language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install pep8
before_script:
  - psql --version
  - psql -U postgres -c 'SELECT version();'
script:
  - ./scripts/cibuild.sh
